export const FETCH_PHONES_SUCCESS:'FETCH_PHONES_SUCCESS' = "FETCH_PHONES_SUCCESS";

export const BREAD_CAMPS_REPLASE:'BREAD_CAMPS_REPLASE' = "BREAD_CAMPS_REPLASE";

export const MAIN_MENU:'MAIN_MENU' = "MAIN_MENU";

export const MAIN_CITY:'MAIN_CITY' = "MAIN_CITY";

export const INPUT_QUESTION:'INPUT_QUESTION' = "INPUT_QUESTION";

export const CLICK_BOARD_MAIN_MENU:'CLICK_BOARD_MAIN_MENU' = "CLICK_BOARD_MAIN_MENU";

export const CHECK_ITEMS_BTN:'CHECK_ITEMS_BTN' = 'CHECK_ITEMS_BTN';

export const FETCH_ITEM:'FETCH_ITEM' = 'FETCH_ITEM';

export const FETCH_LINK_NAVI_MENU:'FETCH_LINK_NAVI_MENU' = 'FETCH_LINK_NAVI_MENU';

export const SERVICE_MENU_DOWN:'SERVICE_MENU_DOWN' = 'SERVICE_MENU_DOWN';

export const MAIN_MENU_DOWN:"MAIN_MENU_DOWN" = 'MAIN_MENU_DOWN';

export const SALE_MENU_DOWN:"SALE_MENU_DOWN" = 'SALE_MENU_DOWN';

export const SERVICE_DATA:"SERVICE_DATA" = 'SERVICE_DATA';

export const ADD_CART_ITEM:"ADD_CART_ITEM" = 'ADD_CART_ITEM';

export const DEL_CART_ITEM:"DEL_CART_ITEM" = 'DEL_CART_ITEM';