export const data = [
	{id: 1, active: true, type: 'active', title: 'Iphone', price: 11000, city: 'Moskov', day: 15, like: 32},
	{id: 2, active: true, type: 'buy', title: 'Readmi', price: 13400, city: 'Moskov', day: 15, like: 32},
	// {id: 3, active: true, type: 'active', title: 'Xiaomi', price: 10000, city: 'Moskov', day: 15, like: 32},
	// {id: 4, active: true, type: 'buy', title: 'Xiaomi', price: 10000, city: 'Moskov', day: 15, like: 32},
	// {id: 5, active: true, type: 'active', title: 'Xiaomi', price: 10000, city: 'Moskov', day: 15, like: 32},
	// {id: 6, active: true, type: 'buy', title: 'Xiaomi', price: 10000, city: 'Moskov', day: 15, like: 32},
	// {id: 7, active: true, type: 'buy', title: 'Xiaomi', price: 10000, city: 'Moskov', day: 15, like: 32},
	// {id: 8, active: true, type: 'buy', title: 'Xiaomi', price: 10000, city: 'Moskov', day: 15, like: 32},
	{id: 9, active: true, type: 'active', title: 'Xiaomi', price: 19000, city: 'Moskov', day: 15, like: 32},
	{id: 10, active: true, type: 'active', title: 'Iphone SE', price: 4400, city: 'Moskov', day: 15, like: 32},
	{id: 11, active: false, type: 'noActive', title: 'Motorolla', price: 19000, city: 'Moskov', day: 15, like: 32},
	// {id: 12, active: false, type: 'buy', title: 'Xiaomi', price: 10000, city: 'Moskov', day: 15, like: 32},
	// {id: 13, active: false, type: 'active', title: 'Xiaomi', price: 10000, city: 'Moskov', day: 15, like: 32},
	// {id: 14, active: false, type: 'active', title: 'Xiaomi', price: 10000, city: 'Moskov', day: 15, like: 32},
	{id: 15, active: false, type: 'active', title: 'Nokia', price: 11000, city: 'Moskov', day: 15, like: 32},
	{id: 16, active: null, type: 'active', title: 'Xiaomi', price: 12000, city: 'Moskov', day: 15, like: 32},
	{id: 17, active: null, type: 'active', title: 'Samsung', price: 10800, city: 'Moskov', day: 15, like: 32},
]