export const rebootItemsData = [
  { title: "Apple", img: "/center/1.png" },
  { title: "Телефоны", img: "/center/2.png" },
  { title: "Планшеты", img: "/center/3.png" },
  { title: "Ноутбуки", img: "/center/4.png" },
  { title: "Моноблоки", img: "/center/5.png" },
  { title: "Мониторы", img: "/center/6.png" },
  { title: "ТВ, аудио", img: "/center/7.png" },
  { title: "Бытовая техника", img: "/center/8.png" },
  { title: "Фото и видео", img: "/center/9.png" },
  { title: "Орг техника", img: "/center/10.png" },
  { title: "Оборудование", img: "/center/11.png" },
  { title: "Инструменты", img: "/center/12.png" },
];

export const malfunctions = [
  "Не работает гнездо зарядки",
  "Не работает аккумулятор",
  "Не работает динамик",
  "Не работает гнездо наушников",
  "Не работает вибрация",
  "Не работает звук",
  "Не работает микрофон",
  "Не работает GPS",
  "Не работает Bluetooth",
  "Не работает гироскоп",
  "Не работает кнопка громкости",
  "Не работают кнопки",
  "Не работает кнопка включения",
  "Не работает кнопка Home",
  "Не работает камера",
  "Не заряжается",
  "Не видит Sim-карту",
  "Не работает Wi-Fi",
];
